// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotesService.DAL;

namespace NotesService.DAL.Migrations
{
    [DbContext(typeof(NotesContext))]
    [Migration("20200617095917_AddKeyToUser")]
    partial class AddKeyToUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NotesService.Domain.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("UserKey")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserKey");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 17, 11, 59, 17, 145, DateTimeKind.Local).AddTicks(1125),
                            ImageData = new byte[] {  },
                            Title = "Test Notitie",
                            UpdatedAt = new DateTime(2020, 6, 17, 11, 59, 17, 148, DateTimeKind.Local).AddTicks(3567),
                            UserId = new Guid("845f9dec-2c0e-4e96-97ef-a0bbb48c3a25")
                        });
                });

            modelBuilder.Entity("NotesService.Domain.Models.User", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Key");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Key = 1,
                            Id = new Guid("845f9dec-2c0e-4e96-97ef-a0bbb48c3a25")
                        });
                });

            modelBuilder.Entity("NotesService.Domain.Models.Note", b =>
                {
                    b.HasOne("NotesService.Domain.Models.User", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserKey");
                });
#pragma warning restore 612, 618
        }
    }
}
